#!/bin/zsh
cd ~/jekyll/projects
for filename in *
do
    if [ $filename != 'kru' ]; then
        if [ $filename != 'ajaxize' ]; then
            if [ $filename != 'nil' ]; then
                echo "$filename"
                sed 's/layout: projects/layout: ajax/' $filename > nil/$filename
            fi
        fi
    fi
done
cd kru
for filename in *
do
    echo "kru/$filename"
    sed 's/layout: projects/layout: ajax/' $filename > ../nil/kru/$filename
done

