#!/bin/zsh
sed 's/%3A/:/g' /home/srv/http/kwpolska/*.html /home/srv/http/kwpolska/*.php /home/srv/http/kwpolska/*/*.html /home/srv/http/kwpolska/*/*.php /home/srv/http/kwpolska/*/*/*.html /home/srv/http/kwpolska/*/*/*.php /home/srv/http/kwpolska/*/*/*/*.html /home/srv/http/kwpolska/*/*/*/*.php /home/srv/http/kwpolska/*/*/*/*/*.html -i
