#!/bin/zsh
cd ~/hyde/content/projects
for filename in *
do
    if [ $filename != 'kru' ]; then
        if [ $filename != 'ajaxize' ]; then
            if [ $filename != 'nil' ]; then
                echo "$filename"
                sed 's/extends: projects.j2/extends: md.j2/' $filename | sed 's/default_block: main_project/default_block: main_md/' > ../media/projects-nil/$filename
            fi
        fi
    fi
done
cd kru
for filename in *
do
    echo "kru/$filename"
    sed 's/extends: projects.j2/extends: md.j2/' $filename | sed 's/default_block: main_project/default_block: main_md/' > ../../media/projects-nil/kru/$filename
done
cp ~/hyde/content/media/projects-nil/kru/index.html ~/hyde/content/media/projects-nil/kru.html
