" Copyright Kwpolska 2011.
set nocompatible
set backspace=indent,eol,start
set numberwidth=1
set showmode
set nobackup
set nowritebackup
set nocp
set fencs=utf-8
set mouse=a
set nu
set is
set nohls
set paste
set wrap
set splitbelow
set splitright
set wildmode=longest,list
set so=7
set softtabstop=4
set shiftwidth=4
set expandtab
set list
set lcs=eol:\ ,tab:·\ ,trail:@
set linebreak
set display+=lastline
set whichwrap=b,s,<,>,h,l
set autoindent
set si
set showcmd
set wildmenu
set ruler
set expandtab
set ignorecase
set smartcase
set showmatch
set encoding=utf-8
set textwidth=79
set history=1000
set wildmenu
set wildmode=list:longest
set ignorecase 
set smartcase
set title
set scrolloff=3
set backspace=indent,eol,start
set hlsearch
set incsearch
set gfn=Monospace\ 10
set shell=/bin/zsh
syntax on
filetype on
filetype plugin on
filetype indent on
colo ron

imap <F2> :set nu!<CR>
map <F2> :set number!<Bar>set number?<CR>
map <F12> :set autoindent!<Bar>set autoindent?<CR>
map <F11> :set hls!<Bar>set hls?<CR>
map <F10> :set paste!<Bar>set paste?<CR>
map <F9>  :set wrap!<Bar>set wrap?<CR>
vnoremap > >gv
vnoremap < <gv
nnoremap ' `
nnoremap ` '
let mapleader = ","
let g:jekyll_path = "/home/Kwpolska/jekyll"
source $HOME/.vim/syntax/markdown.vim

autocmd VimEnter * tab all
autocmd BufAdd * exe 'tablast | tabe "' . expand( "<afile") .'"'
function Eval_line( )
 :let start=line( '.' )
 :exe "!eval" getline(start)
endfunction
map <F3> :call Eval_line()

if has("autocmd")
    autocmd BufEnter * :cd %:p:h
endif

"set lcs=eol:\ 
"set lcs=tab:t
