<?php ob_start(); include('/home/srv/http/kwpolska/contact/antibot.php'); ob_end_flush(); ?><!DOCTYPE html>
<html lang="en" class="no-js">
<head lang="en">
    <meta charset="UTF-8">
    <title>Contact Form — Kw’s Blog</title>
    <meta name="description" content="Want to talk to me?  Go for it.  Here’s the right form.">
    <meta name="author" content="Kwpolska">
    <!--  Mobile viewport optimized: j.mp/bplateviewport -->
    <meta name="viewport" content="">

    <link rel="canonical" href="/">
    <link rel="home" href="http://kwpolska.tk">
    <link rel="prev" href="/">
    <link rel="next" href="/">

        <link rel="shortcut icon" href="http://kwcdn.tk/favicon.ico">
    <link rel="apple-touch-icon" href="http://kwcdn.tk/apple-touch-icon.png">
    
        <link rel="stylesheet" href="http://kwcdn.tk/css/light.min.css">    
        <link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:200,300,400,700,200italic,300italic,400italic,700italic|Droid+Sans+Mono|Raleway:100&subset=latin,latin-ext' rel='stylesheet' type='text/css'>    
          <script src="http://kwcdn.tk/js/libs/modernizr-2.0.6.min.js"></script>
        </head>
<body id="form">
        <header>
                <nav id="sitenav">
            <div id="logo"><a href="http://kwpolska.tk"><img src="http://kwcdn.tk/images/transparent.png" alt="Kw"></a></div>
                                    <ul>
                        <li>
            <a title="Home Page"
                class="menuitem home"
                href="/">
                Home
            </a>
        </li>                <li>
            <a title="Blog"
                class="menuitem blog"
                href="/blog">
                Blog
            </a>
        </li>                <li>
            <a title="Projects"
                class="menuitem projects"
                href="/projects">
                Projects
            </a>
        </li>                <li>
            <a title="KwBot"
                class="menuitem kwbot"
                href="/kwbot">
                KwBot
            </a>
        </li>                <li>
            <a title="Contact"
                class="menuitem contact"
                href="/contact">
                Contact
            </a>
        </li>                <li>
            <a title="Search"
                class="menuitem search"
                href="/search">
                Search
            </a>
        </li>    </ul>
                        <h1 id="sitetitle">Contact Form</h1>
                </nav>
    </header>
    
        <section class="content">
<style>label {display: inline;}</style>
<form action="/contact/send.php" method="post" id="form">
    <article>
        <header><label for="name">From </label><label for="mail">&lt;mail&gt;</label>: <input id="name" name="name" required class="required" style="width: 40%;"> &lt;<input id="mail" name="mail" type="email" required class="email required" style="width: 40%;">&gt;<br>
            <input name="subject" id="subject" required class="required" style="font-weight: bold; font-family: 'Play',sans-serif; font-size: 2em;">
        </header>
        <div class="text clearfix" style="padding: 0;"><textarea name="message" id="message" rows="24" required class="required" style="border: none; width: 100%; height: 100%;"></textarea></div>
        <footer style="height: auto;">
            <label for="vfbpq"><code style="border: none;"><?php echo $_SESSION['let']; ?></code> is the</label> <input id="vfbpq" name="vfbpq" required class="required" style="width: 75px;"> letter of the alphabet.*<br>
            <input type="hidden" name="vfbpjstoken" id="vfbpjstoken" value="<?php echo $_SESSION['vfbpjstoken'] ?>">
            <input type="submit" value="Submit" style="float: right;" id="submit">
            Your IP address will be saved.  All fields are required.<br>* please insert an ordinal number, eg. "first".
        </footer>
    </article>
</form>

    </section>
        <footer>served by nginx, generated by
    hyde<br>copyright&nbsp;©&nbsp;2009-2013&nbsp;Kwpolska<br><a rel="license" href="http://creativecommons.org/licenses/by-nc-nd/3.0/">CC BY-NC-ND</a></footer>
    <!-- Javascript at the bottom for fast page loading -->
        <!-- Grab Google CDN's jQuery, with a protocol relative URL; fall back to local if necessary -->
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="http://kwcdn.tk/js/libs/jquery-1.7.1.min.js">\x3C/script>')</script>
    
        <script type="text/javascript" src="http://kwcdn.tk/fancybox/lib/jquery.mousewheel-3.0.6.pack.js"></script>
    <script type="text/javascript" src="http://kwcdn.tk/fancybox/source/jquery.fancybox.pack.js?v=2.0.5"></script>
    <script type="text/javascript" src="http://kwcdn.tk/fancybox/source/helpers/jquery.fancybox-buttons.js?v=2.0.5"></script>
    <script type="text/javascript" src="http://kwcdn.tk/fancybox/source/helpers/jquery.fancybox-thumbs.js?v=2.0.5"></script>
    <script type="text/javascript">
        $(document).ready(function() {
            $(".fancybox").fancybox({ helpers: { buttons: { position: 'top' }, thumbs: { width: 100, height: 100 } } });
        });
    </script>
    
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.8.16/themes/smoothness/jquery-ui.css" type="text/css">
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.min.js"></script>
<script type="text/javascript">
$(document).ready(function(){
    $("#submit").button();
    $("#abq").autocomplete({
        source: ["first", "second", "third", "fourth", "fifth", "sixth"]
    }, "option", "showAnim", "slideDown");
    $("#form").validate();
});</script>
<!--<script src="http://kwcdn.tk/js/vfbp.js"></script>-->

    <!--[if lt IE 7 ]>
      <script src="js/libs/dd_belatedpng.js"></script>
      <script>DD_belatedPNG.fix('img, .png_bg'); // Fix any <img> or .png_bg bg-images. Also, please read goo.gl/mZiyb </script>
    <![endif]-->

        <!-- asynchronous google analytics: mathiasbynens.be/notes/async-analytics-snippet
       change the UA-XXXXX-X to be your site's ID -->
<script>
    var _gaq = [['_setAccount', 'UA-11937989-1'], ['_trackPageview']];
    (function(d, t) {
    var g = d.createElement(t),
        s = d.getElementsByTagName(t)[0];
    g.async = true;
    g.src = ('https:' == location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    s.parentNode.insertBefore(g, s);
    })(document, 'script');
</script>

<!-- Internet Defense League. -->
<script type="text/javascript">
    window._idl = {};
    _idl.variant = "banner";
    (function() {
        var idl = document.createElement('script');
        idl.type = 'text/javascript';
        idl.async = true;
        idl.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'members.internetdefenseleague.org/include/?url=' + (_idl.url || '') + '&campaign=' + (_idl.campaign || '') + '&variant=' + (_idl.variant || 'banner');
        document.getElementsByTagName('body')[0].appendChild(idl);
    })();
</script>    
</body>
</html>